export const PATHS = {
    empty: "",
    slash: "/",
    auth: "auth",
    login: "login",
    register:"register",
    admin:"admin",
    pageNotFound: "404",
    unauthorized: "unauthorized",
    menuManagement: "menu-management",
    menuList:"menu-list",
    jobAdvert:"jobadvert",
    jobAdvertList:"jobadvert-list",
    candidate:"candidate",
    candidateList:"candidate-list",
    application:"application",
    applicationList:"application-list",
    user:"user",
    userList:"user-list",
    job:"job"
}