export const PATHS = {
    empty: "",
    slash: "/",
    auth: "auth",
    login: "login",
    pageNotFound: "404",
    unauthorized: "unauthorized",
    menuManagement: "menu-management",
    menuList:"menu-list",
    jobAdvert:"jobadvert",
    jobAdvertList:"jobadvert-list",
    candidate:"candidate",
    candidateList:"candidate-list",
    application:"application",
    applicationList:"application-list",
}